//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_CNPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThietBi
    {
        public long Id { get; set; }
        public string Ten { get; set; }
        public string SoSerial { get; set; }
        public Nullable<long> IdNhaCungCap { get; set; }
        public Nullable<int> SoNamBaoHanh { get; set; }
        public Nullable<System.DateTime> NgayMua { get; set; }
        public Nullable<long> IdTrangThai { get; set; }
        public Nullable<long> IdPhong { get; set; }
    
        public virtual NhaCungCap NhaCungCap { get; set; }
        public virtual Phong Phong { get; set; }
        public virtual TrangThaiTB TrangThaiTB { get; set; }
    }
}
